### ISSUE TITLE
broken links - iframe sameorigin header

### ISSUE THREAD

**Issue by ghvaldez** [heroku/wywh#18]
clicking on either of the "login" or "sign up" links do not do anything.  Error console indicates:  "Refused to display 'https://id.heroku.com/login' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'."

**Comment by crcastle** [comment]
Sorry for the problems @ghvaldez.  It looks like this was due to an [emergency maintenance event](https://status.heroku.com/incidents/893).
